version: '3.8'

services:
  activemq:
    image: apache/activemq-classic:latest
    container_name: activemq
    ports:
      - "8161:8161"   # Web Console
      - "61616:61616" # OpenWire
      - "61613:61613" # STOMP (Python connects here)
    restart: unless-stopped

  influxdb:
    image: influxdb:2
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpassword
      - DOCKER_INFLUXDB_INIT_ORG=internship
      - DOCKER_INFLUXDB_INIT_BUCKET=flight_data
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=super-secret-auth-token
    volumes:
      - influxdb-data:/var/lib/influxdb2
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=adminpassword
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - influxdb
    restart: unless-stopped

volumes:
  influxdb-data:
  grafana-data: